# Generated by Django 3.1.5 on 2021-01-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='medicine',
            field=models.ManyToManyField(to='pharma.Medicine'),
        ),
    ]
